schema_version: 1

context:
  version: "1.37.0.8"

package:
  name: lightkube-models
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/l/lightkube-models/lightkube_models-${{ version }}.tar.gz
  sha256: 07a350c76cbf290dd794075ea8e0147ac6cd35297755b391b72676ceef17c858

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pdm-backend
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - lightkube
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Models and Resources for lightkube module
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/gtsystem/lightkube-models

extra:
  recipe-maintainers:
    - janjagusch
